-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    department character varying(50) NOT NULL,
    PRIMARY KEY ("employee_id")
);

CREATE TABLE IF NOT EXISTS public."сategory"
(
    category_id integer NOT NULL,
    category_name character varying(50) NOT NULL,
    description character varying(50) NOT NULL,
    type character varying(50) NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.document
(
    document_id integer NOT NULL,
    employee_id integer NOT NULL,
    category_id integer NOT NULL,
    title character varying(50) NOT NULL,
    description character varying(50) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_updated timestamp with time zone NOT NULL,
    version integer NOT NULL,
    PRIMARY KEY (document_id)
);

CREATE TABLE IF NOT EXISTS public.file
(
    file_id integer NOT NULL,
    document_id integer NOT NULL,
    file_name character varying(50) NOT NULL,
    format character varying(50) NOT NULL,
    size integer NOT NULL,
    upload_date timestamp with time zone NOT NULL,
    PRIMARY KEY (file_id)
);

CREATE TABLE IF NOT EXISTS public.access
(
    access_id integer NOT NULL,
    employee_id integer NOT NULL,
    document_id integer NOT NULL,
    access_level character varying(50) NOT NULL,
    date_granted timestamp with time zone NOT NULL,
    expiry_date timestamp with time zone NOT NULL,
    PRIMARY KEY ("access_id")
);

ALTER TABLE IF EXISTS public.document
    ADD FOREIGN KEY ("employee_id")
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.document
    ADD FOREIGN KEY ("category_id")
    REFERENCES public."сategory" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.file
    ADD FOREIGN KEY ("document_id")
    REFERENCES public.document (document_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.access
    ADD FOREIGN KEY (document_id)
    REFERENCES public.document (document_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.access
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;